name: Close Pull Request

on:
  pull_request_target:
    types:
      - opened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3.1.2
        with:
          comment: |
            Thank you for your pull request. However, you have submitted this PR on the read-only sub split of 'thulium/retrofit-php'.
            Please submit your PR on the https://github.com/thulium/retrofit-php repository.<br><br>
            Thanks!
